services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: doctrs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d doctrs"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_DB: doctrs_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d doctrs_test"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      extra_hosts:
        - "pypi.org:151.101.64.223"
        - "files.pythonhosted.org:151.101.64.223"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/doctrs
      JWT_SECRET_KEY: super-secret-change-me
      SEED_ADMIN_EMAIL: admin@sabina.dev
      SEED_ADMIN_PASSWORD: Admin12345!
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy

  test_runner:
    image: python:3.12-slim
    working_dir: /app
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      TEST_DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres_test:5432/doctrs_test
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres_test:5432/doctrs_test
    volumes:
      - .:/app
    depends_on:
      postgres_test:
        condition: service_healthy

volumes:
  postgres_data:
  postgres_test_data:
